name: Django CI with SQLite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sqlite:
        image: nouchka/sqlite3
        options: >-
          --health-cmd "sqlite3 /tmp/db.sqlite3 .databases"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Up Django Environment
        run: |
          python manage.py migrate
          python manage.py collectstatic --noinput

      - name: Run Tests
        env:
          DJANGO_SETTINGS_MODULE: your_project.settings
          SECRET_KEY: test_secret_key
          DEBUG: true
        run: |
          python manage.py test

      - name: Run Linter
        run: |
          flake8 .

      - name: Run Django Server (For Debugging)
        if: failure()
        run: |
          python manage.py runserver 0.0.0.0:8000
